### ISSUE TITLE
`TokenGenerator`における数値の扱い

### ISSUE THREAD

**Issue by Esu0** [Esu0/meta-assembler#7]
# 問題
現在の`TokenGenerator`は数字を発見した場合、区切り文字が発見されるまで文字を読み取り続け、単純な数字列が得られた場合10進数の数値データを返すようにしている。しかし、gmetaのコード生成ルールの記述では、単純な0と1の列は2進数として扱われるため、パーサによって解決できない問題が生じる。

# 解決策
`TokenGenerator`の機能を拡張したい。拡張案としては、ある期待される動作があったときに、その動作の手助けとなるデータを`TokenGenerator`に送信することによって、処理方法が複数あるパターンを処理する機能の実装が挙げられる。具体的に言えば、外部のメッセージとして、進数を受け取り、直後に数値が来る場合に受け取った進数で処理するような機能があればよい。これはジェネリクスなどで抽象化する必要はない。しかし、機能を`TokenGenerator`のメソッドとして定義してしまうと、パーサは`TokenGenerator`のインスタンスを持つこととなり、パーサの単体テストが困難になる。そこで、機能をトレイトの関数として定義し、そのトレイトを`TokenGenerator`に実装することで、`TokenGenerator`という構造体と`Token`を生成する機能を分離する。すると、パーサが持つ構造体にトレイト境界を設ければ、パーサの定義が可能であり、別の構造体がそのトレイトを実装することで、パーサの単体テストが可能となる。

**Comment by tt6-mzn** [comment]
「01列は2進数で読むように`TokenGenerator`の`next`の中身を変える」みたいな単純なソリューションにしてない理由は、「`#rule_definition`内では01列は2進数で読み、それ以外は十進で読みたい」みたいな需要があるからだと理解したけど、あってる？
トレイトとそのメソッドの仕様もらえれば俺も手伝えるかな

**Comment by Esu0** [comment]
> 「01列は2進数で読むように`TokenGenerator`の`next`の中身を変える」みたいな単純なソリューションにしてない理由は、「`#rule_definition`内では01列は2進数で読み、それ以外は十進で読みたい」みたいな需要があるからだと理解したけど、あってる？ トレイトとそのメソッドの仕様もらえれば俺も手伝えるかな

OK、トレイトの定義を書いてこっちでPull Requestを出すわ

**Comment by Esu0** [comment]
CharGeneratorをPeekableにしたことで解決しそうなのでClose
